apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: new-rs-sensor
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events
  eventBusName: default
  dependencies:
    - name: new-rs
      eventSourceName: new-rs-eventsource
      eventName: app
  triggers:
    - template:
        name: run-promotion-workflow
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: promotion-workflow-
                namespace: argo-workflows
              spec:
                workflowTemplateRef:
                  name: promotion-workflow-template