apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events-addon
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-events
  project: default
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    chart: 'argo-events'
    targetRevision: v1.9.6
    helm:
      releaseName: argo-events
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true