apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: promotion-workflow-template
spec:
  serviceAccountName: argo-workflow
  entrypoint: promotion-rollout
  templates:
    - name: promotion-rollout
      steps:
        - - name: integration
            template: integration-tests
        - - name: promote
            template: promote
            when: "{{steps.integration.outputs.result}} == success"
          - name: aborte
            template: aborte
            when: "{{steps.integration.outputs.result}} == fail"

    - name: integration-tests
      script:
        image: python:3.12
        command: [python]
        source: |
          import time
          import random
          time.sleep(20)
          result = random.choices(["success", "fail"], weights=[0.9, 0.1])[0]
          print(result)

    - name: promote
      container:
        image: quay.io/argoproj/kubectl-argo-rollouts:master
        args: ["promote mock-app-combined-argo-rollout"]

    - name: aborte
      container:
        image: quay.io/argoproj/kubectl-argo-rollouts:master
        args: ["abort mock-app-combined-argo-rollout"]
