apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-addon
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-workflows
  project: default
  sources:
  - repoURL: 'https://argoproj.github.io/argo-helm'
    chart: 'argo-workflows'
    targetRevision: 0.45.14
    helm:
      valueFiles:
      - '$values/values/argo-rollouts-addon-values.yaml'
  - repoURL: 'https://github.com/BENMALEKarim/awesome-app-combined-argo/'
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true