apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: app
  project: default
  sources:
    repoURL: 'https://BENMALEKarim.github.io/awesome-app-helm'
    chart: 'players-info-backend'
    targetRevision: 1.0.0
    helm:
      releaseName: players-info-backend

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true