apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: app
  project: default
  sources:
  - repoURL: 'https://BENMALEKarim.github.io/awesome-app-helm'
    chart: 'players-info-frontend'
    targetRevision: 1.0.0
    helm:
      valueFiles:
      - '$values/values/frontend-values.yaml'
  - repoURL: 'https://github.com/BENMALEKarim/awesome-app-combined-argo/'
    targetRevision: main
    ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true