name: CI pipeline

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'

jobs:  
  build-container-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Run unit tests
      run: echo "building and testing the app ..."

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}/mock-app-combined-argo:${{ github.sha }}
