name: CI pipeline

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'

jobs:  
  build-container-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Run unit tests
      run: echo "building and testing the app ..."

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}/mock-app-argo-combined:${{ github.ref_name }}

    - name: Update Helm values file
      uses: mikefarah/yq@master
      with:
        cmd: yq eval '.image.tag = "{{ github.ref_name }}"' -i "charts/values.yaml"
    
    - name: Commit changes
      run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "New image version: ${{ github.ref_name }} [skip ci]"          
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }